### ISSUE TITLE
mobs not spawning

### ISSUE THREAD

**Issue by GauntAndreX8** [mim1q/MineCells#103]
latest version im using for this mod 1.20.1, mobs wont spawn in the dungeons, when I try with the mod itself it worked fine
Im using forge and fabric connector, not sure if other mods I have interfere with this
Sinytra Connector: 1.0.0-beta.40+1.20.1
		SINYTRA CONNECTOR IS PRESENT!
		Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker.
		Connector's issue tracker can be found at https://github.com/Sinytra/Connector/issues.
		Installed Fabric mods:
		| ================================================== | ============================== | ============================== | ==================== |
		| owo-lib-0.11.2+1.20$jankson-1.2.2_mapped_srg_1.20. | jankson                        | blue_endless_jankson           | 1.2.2                |
		| EndsPhantasm-1.20.1-0.1_mapped_srg_1.20.1.jar      | End's Phantasm                 | phantasm                       | 0.1                  |
		| minecells-1.7.2$omega-config-base-1.2.3-1.18.1_map | OmegaConfig                    | omega_config                   | 1.2.3-1.18.1         |
		| owo-lib-0.11.2+1.20_mapped_srg_1.20.1.jar          | oωo                            | owo                            | 0.11.21.20           |
		| minecells-1.7.2_mapped_srg_1.20.1.jar              | Mine Cells                     | minecells                      | 1.7.2                |
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar mixin-transmogrifier TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar connector_loader TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		lowcodefml@null
	Mod List: 
		saturn-mc1.20.1-0.1.3.jar                         |Saturn                        |saturn                        |0.1.3               |DONE      |Manifest: NOSIGNATURE
		YungsBetterDungeons-1.20-Forge-4.0.3.jar          |YUNG's Better Dungeons        |betterdungeons                |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		habitat-1.3.0.jar                                 |Habitat                       |habitat                       |1.3.0               |DONE      |Manifest: NOSIGNATURE
		secondchanceforge-1.20-1.5.1.jar                  |Second Chance Forge           |secondchanceforge             |1.5.1               |DONE      |Manifest: NOSIGNATURE
		EasyAnvils-v8.0.1-1.20.1-Forge.jar                |Easy Anvils                   |easyanvils                    |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		riverredux-0.3.1.jar                              |RiverRedux                    |riverredux                    |0.3.1               |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |DONE      |Manifest: NOSIGNATURE
		kubejs-bridge-1.10.0+1.20.1.jar                   |Connector Extras KubeJS Bridge|connectorextras_kubejs_bridge |1.10.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		nether-s-exoticism-1.20.1-1.2.7.jar               |Nether's Exoticism            |nethers_exoticism             |1.2.7               |DONE      |Manifest: NOSIGNATURE
		fabric-rendering-fluids-v1-3.0.28+4ac5e37a77.jar  |Fabric Rendering Fluids (v1)  |fabric_rendering_fluids_v1    |3.0.28+4ac5e37a77   |DONE      |Manifest: NOSIGNATURE
		fabric-models-v0-0.4.2+7c3892a477.jar             |Fabric Models (v0)            |fabric_models_v0              |0.4.2+7c3892a477    |DONE      |Manifest: NOSIGNATURE
		Mob+Battle+Extras+1.0.0+-+1.20.1.jar              |MobBattleExtras               |mbextras                      |1.0.0               |DONE      |Manifest: NOSIGNATURE
		hourglass-1.20-1.2.1.1.jar                        |Hourglass                     |hourglass                     |1.2.1.1             |DONE      |Manifest: NOSIGNATURE
		fabric-convention-tags-v1-1.5.5+fa3d1c0177.jar    |Fabric Convention Tags        |fabric_convention_tags_v1     |1.5.5+fa3d1c0177    |DONE      |Manifest: NOSIGNATURE
		fabric-command-api-v1-1.2.34+f71b366f77.jar       |Fabric Command API (v1)       |fabric_command_api_v1         |1.2.34+f71b366f77   |DONE      |Manifest: NOSIGNATURE
		plushie_buddies-0.0.2-1.20.1.jar                  |Plushie Buddies               |plushie_buddies               |0.0.2-1.20.1        |DONE      |Manifest: NOSIGNATURE
		fabric-block-view-api-v2-1.0.1+0767707077.jar     |Fabric BlockView API (v2)     |fabric_block_view_api_v2      |1.0.1+0767707077    |DONE      |Manifest: NOSIGNATURE
		fabric-command-api-v2-2.2.13+561530ec77.jar       |Fabric Command API (v2)       |fabric_command_api_v2         |2.2.13+561530ec77   |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.20-Forge-4.0.3.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		bagus_lib-1.20.1-4.5.4.jar                        |Bagus Lib                     |bagus_lib                     |1.20.1-4.5.4        |DONE      |Manifest: NOSIGNATURE
		rei-bridge-1.10.0+1.20.1.jar                      |Connector Extras REI Bridge   |connectorextras_rei_bridge    |1.10.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.20.1-1.6.4.jar                   |Guard Villagers               |guardvillagers                |1.20.1-1.6.4        |DONE      |Manifest: NOSIGNATURE
		BiomeParticleWeather-v4.1.0-1.20.1-Forge.jar      |Biome Particle Weather        |impactfulweather              |4.1.0               |DONE      |Manifest: NOSIGNATURE
		clickadv-1.20.1-3.7.jar                           |clickadv mod                  |clickadv                      |1.20.1-3.7          |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.2.1.jar                       |Balm                          |balm                          |7.2.1               |DONE      |Manifest: NOSIGNATURE
		fabric-screen-api-v1-2.0.8+45a670a577.jar         |Fabric Screen API (v1)        |fabric_screen_api_v1          |2.0.8+45a670a577    |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.20.1-1.4.0.247.jar          |Just Enough Resources         |jeresources                   |1.4.0.247           |DONE      |Manifest: NOSIGNATURE
		exposure-1.20.1-1.4.1-forge.jar                   |Exposure                      |exposure                      |1.4.1               |DONE      |Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar  |YUNG's Better Nether Fortresse|betterfortresses              |1.20-Forge-2.0.5    |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |DONE      |Manifest: NOSIGNATURE
		sawmill-1.20-1.3.11.jar                           |Universal Sawmill             |sawmill                       |1.20-1.3.11         |DONE      |Manifest: NOSIGNATURE
		geophilic-v2.1.0-mc1.20u1.20.2.jar                |Geophilic                     |geophilic                     |2.1.0-mc1.20u1.20.2 |DONE      |Manifest: NOSIGNATURE
		embeddium-0.3.11+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.3.11+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
		athena-forge-1.20.1-3.1.1.jar                     |Athena                        |athena                        |3.1.1               |DONE      |Manifest: NOSIGNATURE
		terrablender-bridge-1.10.0+1.20.1.jar             |Connector Extras Terrablender |connectorextras_terrablender_b|1.10.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.20.1-2.15.0.jar                   |Structure Gel API             |structure_gel                 |2.15.0              |DONE      |Manifest: NOSIGNATURE
		corpse-1.20.1-1.0.9.jar                           |Corpse                        |corpse                        |1.20.1-1.0.9        |DONE      |Manifest: NOSIGNATURE
		AdvancementPlaques-1.20.1-forge-1.5.1.jar         |Advancement Plaques           |advancementplaques            |1.5.1               |DONE      |Manifest: NOSIGNATURE
		TinySkeletons-v8.0.1-1.20.1-Forge.jar             |Tiny Skeletons                |tinyskeletons                 |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		REBIRTH+Paintings+5.0.0.jar                       |Rebirth: Paintings            |rebirth_paintings             |12.0.0              |DONE      |Manifest: NOSIGNATURE
		fabric-game-rule-api-v1-1.0.40+683d4da877.jar     |Fabric Game Rule API (v1)     |fabric_game_rule_api_v1       |1.0.40+683d4da877   |DONE      |Manifest: NOSIGNATURE
		sleep_tight-1.20-1.1.17.jar                       |Sleep Tight                   |sleep_tight                   |1.20-1.1.17         |DONE      |Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.20.1-2.1.0.jar          |Resourcefulconfig             |resourcefulconfig             |2.1.0               |DONE      |Manifest: NOSIGNATURE
		clustore-1.2.0.jar                                |Clustore                      |clustore                      |1.0.0               |DONE      |Manifest: NOSIGNATURE
		mysticaloaktree-1.20-1.11.jar                     |Mystical Oak Tree             |mysticaloaktree               |1.20-1.11           |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.7.2+1.20.1.jar                     |Curios API                    |curios                        |5.7.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		medieval_seedbags_1.0.0_forge_1.20.1.jar          |Medieval Seedbags             |seedbags                      |1.0.0               |DONE      |Manifest: NOSIGNATURE
		nocube's_villagers_sell_animals_1.2.1_forge_1.20.1|Villagers Sell Animals (by NoC|villagersellanimals           |1.2.1               |DONE      |Manifest: NOSIGNATURE
		salt-1.20.1-1.2.4.jar                             |Salt                          |salt                          |1.2.4               |DONE      |Manifest: NOSIGNATURE
		overweightfarming-1.20.1-2.1.0-forge.jar          |Overweight Farming            |overweight_farming            |1.20.1-2.1.0-forge  |DONE      |Manifest: NOSIGNATURE
		fabric-entity-events-v1-1.6.0+6274ab9d77.jar      |Fabric Entity Events (v1)     |fabric_entity_events_v1       |1.6.0+6274ab9d77    |DONE      |Manifest: NOSIGNATURE
		sapience-1.20.1-1.0.0.jar                         |Sapience                      |sapience                      |1.20.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		YungsBetterEndIsland-1.20-Forge-2.0.5.jar         |YUNG's Better End Island      |betterendisland               |1.20-Forge-2.0.5    |DONE      |Manifest: NOSIGNATURE
		fabric-rendering-data-attachment-v1-0.3.37+a6081af|Fabric Rendering Data Attachme|fabric_rendering_data_attachme|0.3.37+a6081afc77   |DONE      |Manifest: NOSIGNATURE
		the_bumblezone-7.2.21+1.20.1-forge.jar            |The Bumblezone                |the_bumblezone                |7.2.21+1.20.1-forge |DONE      |Manifest: NOSIGNATURE
		Masik'sPuzzleDungeon-forge-1.20.1-v1.1.1.jar      |Masik's Puzzle Dungeon        |masiks_puzzle_dungeon         |1.1.1               |DONE      |Manifest: NOSIGNATURE
		EasyShulkerBoxes-v8.0.0-1.20.1-Forge.jar          |Easy Shulker Boxes            |easyshulkerboxes              |8.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		additionalpaintings_v110_FORGE_1_20_x.jar         |Rispwind's Additional Painting|rw_additionalpaintings        |1.1.0               |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.20-Forge-4.0.4.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.20-Forge-4.0.4    |DONE      |Manifest: NOSIGNATURE
		veinmining-forge-1.3.0+1.20.1.jar                 |Vein Mining                   |veinmining                    |1.3.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		DarkPaintings-Forge-1.20.1-17.0.4.jar             |DarkPaintings                 |darkpaintings                 |17.0.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		YungsBetterJungleTemples-1.20-Forge-2.0.4.jar     |YUNG's Better Jungle Temples  |betterjungletemples           |1.20-Forge-2.0.4    |DONE      |Manifest: NOSIGNATURE
		fabric-client-tags-api-v1-1.1.2+5d6761b877.jar    |Fabric Client Tags            |fabric_client_tags_api_v1     |1.1.2+5d6761b877    |DONE      |Manifest: NOSIGNATURE
		fabric-dimensions-v1-2.1.54+8005d10d77.jar        |Fabric Dimensions API (v1)    |fabric_dimensions_v1          |2.1.54+8005d10d77   |DONE      |Manifest: NOSIGNATURE
		TES-forge-1.20.1-1.5.jar                          |TES                           |tslatentitystatus             |1.5                 |DONE      |Manifest: NOSIGNATURE
		StylishEffects-v8.0.2-1.20.1-Forge.jar            |Stylish Effects               |stylisheffects                |8.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Fastload-Reforged-mc1.20.1-3.4.0.jar              |Fastload-Reforged             |fastload                      |3.4.0               |DONE      |Manifest: NOSIGNATURE
		puzzlesapi-forge-8.0.2.jar                        |Puzzles Api                   |puzzlesapi                    |8.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		wither_drops_netherite_templates_1.0.0_forge_1.20.|Wither Drops Netherite Templat|wither_drops_netherite_templat|1.0.0               |DONE      |Manifest: NOSIGNATURE
		formationsnether-1.0.2.jar                        |Formations Nether             |formationsnether              |1.0.2               |DONE      |Manifest: NOSIGNATURE
		harvestwithease-1.20.1-8.0.1.0-forge.jar          |Harvest with ease             |harvestwithease               |8.0.1.0             |DONE      |Manifest: NOSIGNATURE
		treeharvester-1.20.1-8.3.jar                      |Tree Harvester                |treeharvester                 |8.3                 |DONE      |Manifest: NOSIGNATURE
		fabric-model-loading-api-v1-1.0.3+6274ab9d77.jar  |Fabric Model Loading API (v1) |fabric_model_loading_api_v1   |1.0.3+6274ab9d77    |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		sunflowerdelight-1.20.1-1.0.2.jar                 |Sunflower Delight             |sunflowerdelight              |1.0.2               |DONE      |Manifest: NOSIGNATURE
		AttributeFix-Forge-1.20.1-21.0.4.jar              |AttributeFix                  |attributefix                  |21.0.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		fabric-screen-handler-api-v1-1.3.30+561530ec77.jar|Fabric Screen Handler API (v1)|fabric_screen_handler_api_v1  |1.3.30+561530ec77   |DONE      |Manifest: NOSIGNATURE
		Jellyfishing-2.0.3.jar                            |Jellyfishing                  |jellyfishing                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		goblintraders-forge-1.20.1-1.9.3.jar              |Goblin Traders                |goblintraders                 |1.9.3               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		gnumus_settlement_[Forge]1.20.1_v1.0.jar          |Gnumus Settlement             |gnumus                        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-3.1.0+1.20.jar                       |Caelus API                    |caelus                        |3.1.0+1.20          |DONE      |Manifest: NOSIGNATURE
		Kobolds-2.10.7.jar                                |Kobolds                       |kobolds                       |2.10.7              |DONE      |Manifest: NOSIGNATURE
		fabric-rendering-v1-3.0.8+1c0ea72177.jar          |Fabric Rendering (v1)         |fabric_rendering_v1           |3.0.8+1c0ea72177    |DONE      |Manifest: NOSIGNATURE
		realmrpg_fallen_adventurers_1.0.3_forge_1.20.1.jar|Realm RPG: Fallen Adventurers |realmrpg_skeletons            |1.0.3               |DONE      |Manifest: NOSIGNATURE
		fabric-renderer-indigo-1.5.1+67f9824077.jar       |Fabric Renderer - Indigo      |fabric_renderer_indigo        |1.5.1+67f9824077    |DONE      |Manifest: NOSIGNATURE
		fastasyncworldsave-1.20.1-2.0.jar                 |fastasyncworldsave mod        |fastasyncworldsave            |1.20.1-2.0          |DONE      |Manifest: NOSIGNATURE
		smarterfarmers-1.20-1.7.3.jar                     |Smarter Farmers               |smarterfarmers                |1.20-1.7.3          |DONE      |Manifest: NOSIGNATURE
		what_the_geck_1.0.3.8.jar                         |What The Geck'o               |what_gecko                    |1.0.0               |DONE      |Manifest: NOSIGNATURE
		neruina-1.3.0-forge+1.18.2-1.20.1.jar             |Neruina                       |neruina                       |1.3.0               |DONE      |Manifest: NOSIGNATURE
		geckolib-fabric-compat-1.10.0+1.20.1.jar          |Connector Extras Geckolib-Fabr|connectorextras_geckolib_fabri|1.10.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		snuffles-1.0.7.jar                                |Snuffles                      |snuffles                      |1.0.7               |DONE      |Manifest: NOSIGNATURE
		DeleteWorldsToTrash-v8.0.0-1.20.1-Forge.jar       |Delete Worlds To Trash        |deleteworldstotrash           |8.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		catalogue-forge-1.20.1-1.8.0.jar                  |Catalogue                     |catalogue                     |1.8.0               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		PackingTape-1.20.1-0.14.2.jar                     |Packing Tape                  |packingtape                   |0.14.2              |DONE      |Manifest: NOSIGNATURE
		imst-2.1.0.jar                                    |Immersive Structures          |imst                          |2.1.0               |DONE      |Manifest: NOSIGNATURE
		formations-1.0.2-forge-mc1.20.jar                 |Formations                    |formations                    |1.0.2               |DONE      |Manifest: NOSIGNATURE
		fabric-particles-v1-1.1.2+78e1ecb877.jar          |Fabric Particles (v1)         |fabric_particles_v1           |1.1.2+78e1ecb877    |DONE      |Manifest: NOSIGNATURE
		puzzlesaccessapi-forge-8.0.7.jar                  |Puzzles Access Api            |puzzlesaccessapi              |8.0.7               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		hunters_return-1.20.1-11.4.2.jar                  |Hunters Returns               |hunters_return                |1.20.1-11.4.2       |DONE      |Manifest: NOSIGNATURE
		repair_kits_forge-ver1.1-1.20.1.jar               |Iron Repair Kits              |repair_kits                   |1.1.0               |DONE      |Manifest: NOSIGNATURE
		chalk-1.20.1-1.6.3.jar                            |Chalk                         |chalk                         |1.6.3               |DONE      |Manifest: NOSIGNATURE
		WarriorRage-1.20.1-1.0.0.jar                      |Warrior Rage                  |warriorrage                   |1.0.0               |DONE      |Manifest: NOSIGNATURE
		hearths-v1.0.0-mc1.20u1.20.1.jar                  |Hearths                       |hearths                       |1.0.0-mc1.20u1.20.1 |DONE      |Manifest: NOSIGNATURE
		lucky-block-forge-1.20.1-13.0.jar                 |Lucky Block                   |lucky                         |1.20.1-13.0         |DONE      |Manifest: NOSIGNATURE
		logprot-1.20.1-3.3.jar                            |Logprot                       |logprot                       |1.4                 |DONE      |Manifest: NOSIGNATURE
		trade-cycling-forge-1.20.1-1.0.7.jar              |Trade Cycling                 |trade_cycling                 |1.20.1-1.0.7        |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.0.169.jar           |TerraBlender                  |terrablender                  |3.0.0.169           |DONE      |Manifest: NOSIGNATURE
		fabric-api-base-0.4.31+ef105b4977.jar             |Fabric API Base               |fabric_api_base               |0.4.31+ef105b4977   |DONE      |Manifest: NOSIGNATURE
		Companion-1.20.1-forge-5.0.1.jar                  |Companion                     |companion                     |5.0.1               |DONE      |Manifest: NOSIGNATURE
		bettercombat-forge-1.8.4+1.20.1.jar               |Better Combat                 |bettercombat                  |1.8.4+1.20.1        |DONE      |Manifest: NOSIGNATURE
		combatroll-forge-1.3.1+1.20.1.jar                 |Combat Roll                   |combatroll                    |1.3.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.13.15+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.15+1.20.1      |DONE      |Manifest: NOSIGNATURE
		fabric-block-api-v1-1.0.11+0e6cb7f777.jar         |Fabric Block API (v1)         |fabric_block_api_v1           |1.0.11+0e6cb7f777   |DONE      |Manifest: NOSIGNATURE
		jei-bridge-1.10.0+1.20.1.jar                      |Connector Extras JEI Bridge   |connectorextras_jei_bridge    |1.10.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		fabric-resource-conditions-api-v1-2.3.8+9ad825cd77|Fabric Resource Conditions API|fabric_resource_conditions_api|2.3.8+9ad825cd77    |DONE      |Manifest: NOSIGNATURE
		forgeconfigapiport-1.10.0+1.20.1.jar              |Forge Config API Port (Connect|forgeconfigapiport            |8.0.0               |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.20.1-4.3.jar                      |betterfpsdist mod             |betterfpsdist                 |1.20.1-4.3          |DONE      |Manifest: NOSIGNATURE
		fabric-item-group-api-v1-4.0.12+c9161c2d77.jar    |Fabric Item Group API (v1)    |fabric_item_group_api_v1      |4.0.12+c9161c2d77   |DONE      |Manifest: NOSIGNATURE
		cyclepaintings-1.20.1-3.5.jar                     |Cycle Paintings               |cyclepaintings                |3.5                 |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-1.6.2-mc1.20.1.jar            |EntityCulling                 |entityculling                 |1.6.2               |DONE      |Manifest: NOSIGNATURE
		backpacked-forge-1.20.1-2.2.5.jar                 |Backpacked                    |backpacked                    |2.2.5               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		canary-mc1.20.1-0.3.3.jar                         |Canary                        |canary                        |0.3.3               |DONE      |Manifest: NOSIGNATURE
		fabric-registry-sync-v0-2.3.3+1c0ea72177.jar      |Fabric Registry Sync (v0)     |fabric_registry_sync_v0       |2.3.3+1c0ea72177    |DONE      |Manifest: NOSIGNATURE
		ImmediatelyFast-Forge-1.2.11+1.20.4.jar           |ImmediatelyFast               |immediatelyfast               |1.2.11+1.20.4       |DONE      |Manifest: NOSIGNATURE
		owo-lib-0.11.2+1.20$jankson-1.2.2_mapped_srg_1.20.|jankson                       |blue_endless_jankson          |1.2.2               |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.20.1-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		fabric-recipe-api-v1-1.0.21+514a076577.jar        |Fabric Recipe API (v1)        |fabric_recipe_api_v1          |1.0.21+514a076577   |DONE      |Manifest: NOSIGNATURE
		fabric-object-builder-api-v1-11.1.3+2174fc8477.jar|Fabric Object Builder API (v1)|fabric_object_builder_api_v1  |11.1.3+2174fc8477   |DONE      |Manifest: NOSIGNATURE
		rubidium-extra-0.5.4.2+mc1.20.1-build.118.jar     |Embeddium Extra               |embeddium_extra               |0.5.4.2+mc1.20.1-bui|DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v8.1.17-1.20.1-Forge.jar               |Puzzles Lib                   |puzzleslib                    |8.1.17              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		FriendlyFire-Forge-1.20.1-18.0.6.jar              |FriendlyFire                  |friendlyfire                  |18.0.6              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		bettergolem-1.20.1-4.0.0.jar                      |Better Golem                  |bettergolem                   |1.20.1-4.0.0        |DONE      |Manifest: NOSIGNATURE
		fabric-sound-api-v1-1.0.13+4f23bd8477.jar         |Fabric Sound API (v1)         |fabric_sound_api_v1           |1.0.13+4f23bd8477   |DONE      |Manifest: NOSIGNATURE
		fabric-message-api-v1-5.1.9+52cc178c77.jar        |Fabric Message API (v1)       |fabric_message_api_v1         |5.1.9+52cc178c77    |DONE      |Manifest: NOSIGNATURE
		goated-1.20-1.3.4.jar                             |You've Goat to be kidding me  |goated                        |1.20-1.3.4          |DONE      |Manifest: NOSIGNATURE
		cosmeticarmorreworked-1.20.1-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.20.1-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		EndsPhantasm-1.20.1-0.1_mapped_srg_1.20.1.jar     |End's Phantasm                |phantasm                      |0.1                 |DONE      |Manifest: NOSIGNATURE
		Wealthy+And+Growth-1.20.1-3.1.0.jar               |Wealthy And Growth            |wealthy_and_growth            |1.20.1-3.1.0        |DONE      |Manifest: NOSIGNATURE
		unusualfishmod-1.0.4.jar                          |Unusual Fish Mod              |unusualfishmod                |1.0.4               |DONE      |Manifest: NOSIGNATURE
		fabric-renderer-api-v1-3.2.1+1d29b44577.jar       |Fabric Renderer API (v1)      |fabric_renderer_api_v1        |3.2.1+1d29b44577    |DONE      |Manifest: NOSIGNATURE
		netherportalfix-forge-1.20-13.0.0.jar             |NetherPortalFix               |netherportalfix               |13.0.0              |DONE      |Manifest: NOSIGNATURE
		mobbattle-1.20.1-2.4.7-forge.jar                  |Mob Battle Mod                |mobbattle                     |1.20.1-2.4.7        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.4.2.jar                   |GeckoLib 4                    |geckolib                      |4.4.2               |DONE      |Manifest: NOSIGNATURE
		minecells-1.7.2$omega-config-base-1.2.3-1.18.1_map|OmegaConfig                   |omega_config                  |1.2.3-1.18.1        |DONE      |Manifest: NOSIGNATURE
		fabric-item-api-v1-2.1.28+2272fc7f77.jar          |Fabric Item API (v1)          |fabric_item_api_v1            |2.1.28+2272fc7f77   |DONE      |Manifest: NOSIGNATURE
		IllagerInvasion-v8.0.4-1.20.1-Forge.jar           |Illager Invasion              |illagerinvasion               |8.0.4               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		ants-1.20.1-forge-ver2.1.jar                      |Ants Unleashed                |ants_unleashed                |1.0.0               |DONE      |Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.20-Forge-3.0.3.jar    |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.20-Forge-3.0.3    |DONE      |Manifest: NOSIGNATURE
		gpumemleakfix-1.20.1-1.8.jar                      |Gpu memory leak fix           |gpumemleakfix                 |1.20.1-1.8          |DONE      |Manifest: NOSIGNATURE
		structureessentials-1.20.1-3.2.jar                |Structure Essentials mod      |structureessentials           |1.20.1-3.2          |DONE      |Manifest: NOSIGNATURE
		Prism-1.20.1-forge-1.0.5.jar                      |Prism                         |prism                         |1.0.5               |DONE      |Manifest: NOSIGNATURE
		citadel-2.5.4-1.20.1.jar                          |Citadel                       |citadel                       |2.5.4               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.8.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.8              |DONE      |Manifest: NOSIGNATURE
		cloudstorage-1.4.0-1.20.jar                       |Cloud Storage                 |cloudstorage                  |1.4.0               |DONE      |Manifest: NOSIGNATURE
		iwannaskate-1.2.0.jar                             |I Wanna Skate                 |iwannaskate                   |1.2.0               |DONE      |Manifest: NOSIGNATURE
		domesticationinnovation-1.7.1-1.20.1.jar          |Domestication Innovation      |domesticationinnovation       |1.7.1               |DONE      |Manifest: NOSIGNATURE
		all_bark_all_bite-1.20.1-1.0.2.jar                |All Bark, All Bite            |all_bark_all_bite             |1.20.1-1.0.2        |DONE      |Manifest: NOSIGNATURE
		fabric-data-attachment-api-v1-1.0.0+30ef839e77.jar|Fabric Data Attachment API (v1|fabric_data_attachment_api_v1 |1.0.0+30ef839e77    |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.1.9.jar                 |Bookshelf                     |bookshelf                     |20.1.9              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Random Crits 1.2.5 - 1.20.1.jar                   |Random Crits                  |random_crits                  |1.2.5               |DONE      |Manifest: NOSIGNATURE
		continuity-compat-1.10.0+1.20.1.jar               |Connector Extras Continuity Co|connectorextras_continuity_com|1.10.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		royal_variations_[Forge]_1.20.1_1.0.jar           |Royal Variations              |royalvariations               |1.0.0               |DONE      |Manifest: NOSIGNATURE
		relics-1.20.1-0.6.3.jar                           |Relics                        |relics                        |0.6.3               |DONE      |Manifest: NOSIGNATURE
		wares-1.20.1-1.2.6.jar                            |Wares                         |wares                         |1.2.6               |DONE      |Manifest: NOSIGNATURE
		monobank-1.20.1-1.1.4.jar                         |Monobank                      |monobank                      |1.1.4               |DONE      |Manifest: NOSIGNATURE
		ramcompat-1.20.1-0.1.2.jar                        |RAM-Compat                    |ramcompat                     |0.1.2               |DONE      |Manifest: NOSIGNATURE
		FpsReducer2-forge-1.20-2.5.jar                    |FPS Reducer                   |fpsreducer                    |1.20-2.5            |DONE      |Manifest: NOSIGNATURE
		carryon-forge-1.20.1-2.1.2.7.jar                  |Carry On                      |carryon                       |2.1.2.7             |DONE      |Manifest: NOSIGNATURE
		ShieldExpansion-1.20.1-1.1.7a.jar                 |Shield Expansion              |shieldexp                     |1.1.7a              |DONE      |Manifest: NOSIGNATURE
		SpelunkersCharm-3.5.9-1.20.1.jar                  |Spelunker's Charm             |spelunkers_charm              |3.5.9               |DONE      |Manifest: NOSIGNATURE
		fabric-api-0.92.0+1.11.3+1.20.1.jar               |Forgified Fabric API          |fabric_api                    |0.92.0+1.11.3+1.20.1|DONE      |Manifest: NOSIGNATURE
		dummmmmmy-1.20-1.8.5.jar                          |MmmMmmMmmmmm                  |dummmmmmy                     |1.20-1.8.5          |DONE      |Manifest: NOSIGNATURE
		modmenu-bridge-1.10.0+1.20.1.jar                  |Connector Extras ModMenu Bridg|connectorextras_modmenu_bridge|1.10.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		fabric-content-registries-v0-4.0.11+a670df1e77.jar|Fabric Content Registries (v0)|fabric_content_registries_v0  |4.0.11+a670df1e77   |DONE      |Manifest: NOSIGNATURE
		EnemyExpansion-1.20.1-2.1.0.jar                   |Enemy Expansion               |enemyexpansion                |2.1.0               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.4.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |DONE      |Manifest: NOSIGNATURE
		casualness_delight-1.20.1-0.4n.jar                |Casualness Delight            |casualness_delight            |1.20.1-0.4n         |DONE      |Manifest: NOSIGNATURE
		chefs-delight-1.0.3-forge-1.20.1.jar              |Chefs Delight                 |chefsdelight                  |1.0.3-forge-1.20.1  |DONE      |Manifest: NOSIGNATURE
		curious_armor_stands-1.20-5.0.1.jar               |Curious Armor Stands          |curious_armor_stands          |1.20-5.0.1          |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.3.9_mc1.20.1.jar           |AmbientSounds                 |ambientsounds                 |5.3.9               |DONE      |Manifest: NOSIGNATURE
		fabric-api-lookup-api-v1-1.6.36+67f9824077.jar    |Fabric API Lookup API (v1)    |fabric_api_lookup_api_v1      |1.6.36+67f9824077   |DONE      |Manifest: NOSIGNATURE
		endersdelight-1.20.1-1.0.3.jar                    |Ender's Delight               |endersdelight                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-forge-1.20.1-1.1.1.jar       |Valhelsia Structures          |valhelsia_structures          |1.20.1-1.1.1        |DONE      |Manifest: NOSIGNATURE
		Sniffer+-forge-1.20.1-0.2.0.jar                   |Hellion's Sniffer+            |snifferplus                   |0.2.0               |DONE      |Manifest: NOSIGNATURE
		reach-entity-attributes-2.4.0.jar                 |Reach Entity Attributes       |reach_entity_attributes       |2.4.0               |DONE      |Manifest: NOSIGNATURE
		architectury-bridge-1.10.0+1.20.1.jar             |Connector Extras Architectury |connectorextras_architectury_b|1.10.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		L_Enders_Cataclysm-1.90+-1.20.1.jar               |Cataclysm Mod                 |cataclysm                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		cullleaves-forge-3.2.0.jar                        |CullLeaves                    |cullleaves                    |3.2.0               |DONE      |Manifest: NOSIGNATURE
		midnightlib-forge-1.4.1.jar                       |MidnightLib                   |midnightlib                   |1.4.1               |DONE      |Manifest: NOSIGNATURE
		collective-1.20.1-7.40.jar                        |Collective                    |collective                    |7.40                |DONE      |Manifest: NOSIGNATURE
		realmrpg_seadwellers_2.9.9_forge_1.20.1.jar       |Realm RPG: Sea Dwellers       |seadwellers                   |2.9.9               |DONE      |Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.20-1.9.0.jar            |Better Third Person           |betterthirdperson             |1.9.0               |DONE      |Manifest: NOSIGNATURE
		Connector-1.0.0-beta.40+1.20.1-mod.jar            |Connector                     |connectormod                  |1.0.0-beta.40+1.20.1|DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.20-Forge-4.0.3.jar       |YUNG's Better Strongholds     |betterstrongholds             |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.23.jar            |Resourceful Lib               |resourcefullib                |2.1.23              |DONE      |Manifest: NOSIGNATURE
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |DONE      |Manifest: NOSIGNATURE
		helpwanted_1_20_forge-1.2.0.jar                   |Help Wanted                   |helpwanted                    |1.2.0               |DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.20-0.5.2.jar                    |AI-Improvements               |aiimprovements                |0.5.2               |DONE      |Manifest: NOSIGNATURE
		fabric-loot-api-v2-1.2.1+eb28f93e77.jar           |Fabric Loot API (v2)          |fabric_loot_api_v2            |1.2.1+eb28f93e77    |DONE      |Manifest: NOSIGNATURE
		cupboard-1.20.1-2.6.jar                           |Cupboard utilities            |cupboard                      |1.20.1-2.6          |DONE      |Manifest: NOSIGNATURE
		ConnectorExtras-1.10.0+1.20.1.jar                 |Connector Extras              |connectorextras               |1.10.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		fabric-networking-api-v1-1.3.11+503a202477.jar    |Fabric Networking API (v1)    |fabric_networking_api_v1      |1.3.11+503a202477   |DONE      |Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.6.26.jar                 |Framework                     |framework                     |0.6.26              |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		enchantwithmob-1.20.1-11.7.3.jar                  |EnchantWithMob                |enchantwithmob                |1.20.1-11.7.3       |DONE      |Manifest: NOSIGNATURE
		Species-1.20.1-1.3-Forge.jar                      |Species                       |species                       |1.20.1-1.3          |DONE      |Manifest: NOSIGNATURE
		fabric-lifecycle-events-v1-2.2.22+afab492177.jar  |Fabric Lifecycle Events (v1)  |fabric_lifecycle_events_v1    |2.2.22+afab492177   |DONE      |Manifest: NOSIGNATURE
		muffins_picnic-1.0.0-forge.jar                    |Muffin's Picnic               |muffins_picnic                |1.0.0               |DONE      |Manifest: NOSIGNATURE
		TradingPost-v8.0.2-1.20.1-Forge.jar               |Trading Post                  |tradingpost                   |8.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		fabric-key-binding-api-v1-1.0.37+561530ec77.jar   |Fabric Key Binding API (v1)   |fabric_key_binding_api_v1     |1.0.37+561530ec77   |DONE      |Manifest: NOSIGNATURE
		fabric-transfer-api-v1-3.3.4+b00938ec77.jar       |Fabric Transfer API (v1)      |fabric_transfer_api_v1        |3.3.4+b00938ec77    |DONE      |Manifest: NOSIGNATURE
		owo-lib-0.11.2+1.20_mapped_srg_1.20.1.jar         |oωo                           |owo                           |0.11.21.20          |DONE      |Manifest: NOSIGNATURE
		octolib-1.20.1-0.3.jar                            |OctoLib                       |octolib                       |0.3                 |DONE      |Manifest: NOSIGNATURE
		EasyMagic-v8.0.1-1.20.1-Forge.jar                 |Easy Magic                    |easymagic                     |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		pehkui-bridge-1.10.0+1.20.1.jar                   |Connector Extras Pehkui Bridge|connectorextras_pehkui_bridge |1.10.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		the-conjurer-1.20.1-1.1.6.jar                     |The Conjurer                  |conjurer_illager              |1.1.6               |DONE      |Manifest: NOSIGNATURE
		fabric-resource-loader-v0-0.11.10+cefbb70477.jar  |Fabric Resource Loader (v0)   |fabric_resource_loader_v0     |0.11.10+cefbb70477  |DONE      |Manifest: NOSIGNATURE
		map_atlases-1.20-6.0.2.jar                        |Map Atlases                   |map_atlases                   |1.20-6.0.2          |DONE      |Manifest: NOSIGNATURE
		Structory_Towers_1.20.2_v1.0.5.jar                |Structory: Towers             |structorytowers               |1.0.5               |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.1.3.jar                   |Waystones                     |waystones                     |14.1.3              |DONE      |Manifest: NOSIGNATURE
		TaxFreeLevels-1.3.9-forge-1.20.2.jar              |Tax Free Levels               |taxfreelevels                 |1.3.9               |DONE      |Manifest: NOSIGNATURE
		MerchantMarkers-1.20.1-forge-1.3.3.jar            |Merchant Markers              |merchantmarkers               |1.3.3               |DONE      |Manifest: NOSIGNATURE
		Structory_1.20.2_v1.3.3.jar                       |Structory                     |structory                     |1.3.3               |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.5-1.20.1forge.jar               |Macaw's Paintings             |mcwpaintings                  |1.0.5               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.20.1-12.0.0.3.jar                  |Clumps                        |clumps                        |12.0.0.3            |DONE      |Manifest: NOSIGNATURE
		fabric-mining-level-api-v1-2.1.50+561530ec77.jar  |Fabric Mining Level API (v1)  |fabric_mining_level_api_v1    |2.1.50+561530ec77   |DONE      |Manifest: NOSIGNATURE
		breezy-1.20.1-1.1.1.jar                           |Breezy                        |breezy                        |1.1.1               |DONE      |Manifest: NOSIGNATURE
		configured-forge-1.20.1-2.2.2.jar                 |Configured                    |configured                    |2.2.2               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		Dungeon+Crawl-1.20.1-2.3.14.jar                   |Dungeon Crawl                 |dungeoncrawl                  |2.3.14              |DONE      |Manifest: NOSIGNATURE
		BetterTotemOfUndying-Forge-1.20.1-1.1.0.jar       |Better Totem Of Undying       |better_totem_of_undying       |1.1.0               |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.20-Forge-3.0.3.jar     |YUNG's Better Desert Temples  |betterdeserttemples           |1.20-Forge-3.0.3    |DONE      |Manifest: NOSIGNATURE
		HopoBetterUnderwaterRuins-[1.20-1.20.2]-1.1.4b.jar|HopoBetterUnderwaterRuins     |hopour                        |1.1.4               |DONE      |Manifest: NOSIGNATURE
		BOMD-Forge-1.20.1-1.0.6.jar                       |Bosses of Mass Destruction    |bosses_of_mass_destruction    |1.0.6               |DONE      |Manifest: NOSIGNATURE
		blueprint-1.20.1-7.0.1.jar                        |Blueprint                     |blueprint                     |7.0.1               |DONE      |Manifest: NOSIGNATURE
		energy-bridge-1.10.0+1.20.1.jar                   |Connector Extras Energy Bridge|connectorextras_energy_bridge |1.10.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		minecells-1.7.2_mapped_srg_1.20.1.jar             |Mine Cells                    |minecells                     |1.7.2               |DONE      |Manifest: NOSIGNATURE
		TravelersTitles-1.20-Forge-4.0.1.jar              |Traveler's Titles             |travelerstitles               |1.20-Forge-4.0.1    |DONE      |Manifest: NOSIGNATURE
		fabric-transitive-access-wideners-v1-4.3.1+1880499|Fabric Transitive Access Widen|fabric_transitive_access_widen|4.3.1+1880499877    |DONE      |Manifest: NOSIGNATURE
		nyfsspiders-forge-1.20.1-2.1.1.jar                |Nyf's Spiders                 |nyfsspiders                   |2.1.1               |DONE      |Manifest: NOSIGNATURE
		illagersweararmor-1.20-1.3.1.jar                  |Illagers Wear Armor           |zillagersweararmor            |1.20-1.3.1          |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		alexscaves-1.1.4.jar                              |Alex's Caves                  |alexscaves                    |1.1.4               |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.20.1-17.0.13.jar  |EnchantmentDescriptions       |enchdesc                      |17.0.13             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		moonlight-1.20-2.11.4-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.11.4         |DONE      |Manifest: NOSIGNATURE
		moyai-1.20-2.1.3.jar                              |Moyai                         |moyai                         |1.20-2.1.3          |DONE      |Manifest: NOSIGNATURE
		endermanoverhaul-forge-1.20.1-1.0.3.jar           |Enderman Overhaul             |endermanoverhaul              |1.0.3               |DONE      |Manifest: NOSIGNATURE
		babyfat-1.0.0.jar                                 |Baby Fat                      |babyfat                       |1.0.0               |DONE      |Manifest: NOSIGNATURE
		netherdungeons-1.1.0-alpha2.jar                   |Nether Dungeons               |netherdungeons                |1.1.0-alpha2        |DONE      |Manifest: NOSIGNATURE
		MagnumTorch-v8.0.1-1.20.1-Forge.jar               |Magnum Torch                  |magnumtorch                   |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		gardens-of-the-dead-forge-4.0.1.jar               |Gardens of the Dead           |gardens_of_the_dead           |4.0.1               |DONE      |Manifest: NOSIGNATURE
		fabric-blockrenderlayer-v1-1.1.41+1d0da21e77.jar  |Fabric BlockRenderLayer Regist|fabric_blockrenderlayer_v1    |1.1.41+1d0da21e77   |DONE      |Manifest: NOSIGNATURE
		mixinsquared-forge-0.1.1.jar                      |MixinSquared                  |mixinsquared                  |0.1.1               |DONE      |Manifest: NOSIGNATURE
		amecsapi-1.5.3+mc1.20-pre1.jar                    |Amecs API                     |amecsapi                      |1.5.3+mc1.20-pre1   |DONE      |Manifest: NOSIGNATURE
		betterfarmerscombat-1.1-1.20.1.jar                |Better Farmer's Combat        |betterfarmerscombat           |1.1                 |DONE      |Manifest: NOSIGNATURE
		HopoBetterRuinedPortals-[1.20-1.20.2]-1.3.7.jar   |HopoBetterRuinedPortals       |hoporp                        |1.3.7               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.25_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.25             |DONE      |Manifest: NOSIGNATURE
		tradersindisguise-1.5-1.20.1.jar                  |Traders in Disguise           |tradersindisguise             |1.5                 |DONE      |Manifest: NOSIGNATURE
		smoothboot-mc1.20.1-0.0.3.jar                     |Smooth Boot (Reloaded)        |smoothboot                    |0.0.3               |DONE      |Manifest: NOSIGNATURE
		nethersdelight-1.20.1-4.0.jar                     |Nether's Delight              |nethersdelight                |1.20.1-4.0          |DONE      |Manifest: NOSIGNATURE
		camps_castles_carriages-2.2.jar                   |Camps. Castles. Carriages.    |mr_camps_castles_carriages    |2.2                 |DONE      |Manifest: NOSIGNATURE
		BarteringStation-v8.0.0-1.20.1-Forge.jar          |Bartering Station             |barteringstation              |8.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Iceberg-1.20.1-forge-1.1.21.jar                   |Iceberg                       |iceberg                       |1.1.21              |DONE      |Manifest: NOSIGNATURE
		LegendaryTooltips-1.20.1-forge-1.4.5.jar          |Legendary Tooltips            |legendarytooltips             |1.4.5               |DONE      |Manifest: NOSIGNATURE
		CerbonsBetterBeacons-Forge-1.20.1-1.0.2.jar       |CERBON's Better Beacons       |better_beacons                |1.0.2               |DONE      |Manifest: NOSIGNATURE
		irons_spellbooks-1.20.1-3.1.1.jar                 |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.20.1-3.1.1        |DONE      |Manifest: NOSIGNATURE
		betterarcheology-1.1.6-1.20.1.jar                 |Better Archeology             |betterarcheology              |1.1.6-1.20.1        |DONE      |Manifest: NOSIGNATURE
		fabric-biome-api-v1-13.0.13+dd0389a577.jar        |Fabric Biome API (v1)         |fabric_biome_api_v1           |13.0.13+dd0389a577  |DONE      |Manifest: NOSIGNATURE
		EndlessBiomes 1.5.0 - 1.20.1.jar                  |EndlessBiomes                 |endlessbiomes                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		BetterTridents-v8.0.1-1.20.1-Forge.jar            |Better Tridents               |bettertridents                |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		creeperoverhaul-3.0.2-forge.jar                   |Creeper Overhaul              |creeperoverhaul               |3.0.2               |DONE      |Manifest: NOSIGNATURE
		alexsdelight-1.5.jar                              |Alex's Delight                |alexsdelight                  |1.5                 |DONE      |Manifest: NOSIGNATURE
		ferritecore-6.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		Enhanced_Celestials-forge-1.20.1-5.0.0.2.jar      |Enhanced Celestials           |enhancedcelestials            |5.0.0.2             |DONE      |Manifest: NOSIGNATURE
		CorgiLib-forge-1.20.1-4.0.0.4.jar                 |CorgiLib                      |corgilib                      |4.0.0.4             |DONE      |Manifest: NOSIGNATURE
		emi-bridge-1.10.0+1.20.1.jar                      |Connector Extras EMI Bridge   |connectorextras_emi_bridge    |1.10.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-forge-1.20.1-1.1.1.jar             |Valhelsia Core                |valhelsia_core                |1.1.1               |DONE      |Manifest: NOSIGNATURE
		healingcampfire-1.20.1-5.2.jar                    |Healing Campfire              |healingcampfire               |5.2                 |DONE      |Manifest: NOSIGNATURE
		fabric-data-generation-api-v1-12.3.4+369cb3a477.ja|Fabric Data Generation API (v1|fabric_data_generation_api_v1 |12.3.4+369cb3a477   |DONE      |Manifest: NOSIGNATURE
		fabric-events-interaction-v0-0.6.2+0d0bd5a777.jar |Fabric Events Interaction (v0)|fabric_events_interaction_v0  |0.6.2+0d0bd5a777    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 4f06aeda-c01f-4e58-9069-5dcbc1844c40
	FML: 47.2
	Forge: net.minecraftforge:47.2.0

**Comment by mim1q** [comment]
I know this may be obvious, but are you in Peaceful difficulty? Had a similar report recently and that turned out to be the issue :sweat_smile: 

Also, some more details would be helpful: 
1. Did it only work with just Mine Cells, owo and Fabric, or did it also work with those *and Connector*?
2. Do the spawners "pop" and then not spawn anything, or do they just stay floating in the air and don't even react to players coming closer?

**Comment by GauntAndreX8** [comment]
I wasn’t in peaceful, I was in normal difficulty 
It worked when I only used connector, OwO, and mine cells since I’m playing on forge
The spawners just stayed floating not reacting to the player even when being close to it

**Comment by mim1q** [comment]
Do the logs display any errors or warnings from Mine Cells, maybe something about invalid Spawner Rune IDs?

I don't have the means nor time to verify all of the mods you have installed. The best course of action for you would be to remove them a few at a time, and figure out which one could be the culprit from there. If you manage to find it, let me know here and I'll try to see if this issue can be resolved on my end :grin:

**Comment by GauntAndreX8** [comment]
No they display no logs or warnings
I found what caused it, it's the Blueprint mod from abnormals, when I use it it causes it but when I remove it, it's back to normal

**Comment by GauntAndreX8** [comment]
not being rude or rushing but will the bug be solved in the next or future update?

**Comment by mim1q** [comment]
Hey, I haven't found the issue by browsing Blueprint's code, yet. And it's hard for me to actively debug it because it's a Forge mod and my development environment is Fabric, of course. I'll see what I can do on my side, and if there's any obvious fix I'll try to include it in the next release, which should be coming in the following few weeks

**Comment by GauntAndreX8** [comment]
Good news bud, with the blueprint latest update, the big is finally fixed, you no longer need to focus on this anymore but thanks for the support anyways

**Comment by Terra-B-Welch** [comment]
> Good news bud, with the blueprint latest update, the big is finally fixed, you no longer need to focus on this anymore but thanks for the support anyways

you sure it's blueprint? As I have the same problem but updating blueprint did not fix it...

**Comment by GauntAndreX8** [comment]
Well the problem is fixed when I did
